mariadb:
  database: my_database
  enabled: false
  port: '3306'
  root_password: root_password
  user: my_user
minio:
  console_port: '9001'
  enabled: true
  port: '9000'
  root_password: miniosecret
  root_user: minio
mysql:
  database: my_database
  enabled: false
  port: '3306'
  root_password: my_root_password
  user: my_user
postgresql:
  database: my_database
  enabled: true
  password: my_password
  port: '5432'
  username: postgres
redis:
  enabled: false
  password: my_password
  port: '6379'
